/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search customers by name or email prefix, paged.
         * @description `search` matches names or emails that start with the text. `pageSize` is at most 100.
         *                 `sort` is `name` (default) or `createdAt`; prefix with `-` for descending.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Matches customers whose name or email <b>starts with</b> this text (case-insensitive). */
                    search?: string;
                    /** @description `name` (default) or `createdAt`; prefix with `-` for descending. */
                    sort?: string;
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Items per page, 1 to 100. */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerResponsePagedResult"];
                        "application/json": components["schemas"]["CustomerResponsePagedResult"];
                        "text/json": components["schemas"]["CustomerResponsePagedResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a customer.
         * @description The email is stored lower-cased and must be unique. The country must be a SADC member state; it decides which
         *     currencies the customer may order in.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCustomerRequest"];
                    "text/json": components["schemas"]["CreateCustomerRequest"];
                    "application/*+json": components["schemas"]["CreateCustomerRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerResponse"];
                        "application/json": components["schemas"]["CustomerResponse"];
                        "text/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a customer by ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerResponse"];
                        "application/json": components["schemas"]["CustomerResponse"];
                        "text/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a development token with the requested roles. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DevTokenRequest"];
                    "text/json": components["schemas"]["DevTokenRequest"];
                    "application/*+json": components["schemas"]["DevTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DevTokenResponse"];
                        "application/json": components["schemas"]["DevTokenResponse"];
                        "text/json": components["schemas"]["DevTokenResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders, filtered and sorted, paged.
         * @description Filter by `customerId` and/or `status`. `sort` is `createdAt` or `total`; prefix with
         *     `-` for descending (default `-createdAt`, newest first). `pageSize` is at most 100.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Only this customer's orders. */
                    customerId?: string;
                    /** @description Pending, Paid, Fulfilled or Cancelled (case-insensitive). */
                    status?: string;
                    /** @description `createdAt` or `total`; prefix with `-` for descending. Default `-createdAt` (newest first). */
                    sort?: string;
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Items per page, 1 to 100. */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderSummaryResponsePagedResult"];
                        "application/json": components["schemas"]["OrderSummaryResponsePagedResult"];
                        "text/json": components["schemas"]["OrderSummaryResponsePagedResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an order.
         * @description The server validates the customer and the currency (it must be permitted for the customer's country), checks each
         *     line, and computes `totalAmount`. New orders start `Pending`. Returns the order with its `ETag`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                    "text/json": components["schemas"]["CreateOrderRequest"];
                    "application/*+json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderResponse"];
                        "application/json": components["schemas"]["OrderResponse"];
                        "text/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an order with its line items.
         * @description Responses carry an `ETag`. Send it back as `If-None-Match` to get `304 Not Modified` (no body) when
         *     the order hasn't changed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderResponse"];
                        "application/json": components["schemas"]["OrderResponse"];
                        "text/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Not Modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change an order's status (idempotent).
         * @description Allowed: Pending → Paid | Cancelled, Paid → Fulfilled (once stock is allocated) | Cancelled.
         *
         *     <b>Idempotency-Key</b> (required): a unique value such as a UUID, chosen per intended change. Retrying with the
         *                 same key and body returns the original response (header `Idempotent-Replayed: true`) without applying it
         *                 again. Reusing a key for a different request returns 422. Keys are kept for 24 hours.
         *
         *     <b>If-Match</b> (optional): the ETag you last saw. If the order changed since, you get 412.
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateOrderStatusRequest"];
                    "text/json": components["schemas"]["UpdateOrderStatusRequest"];
                    "application/*+json": components["schemas"]["UpdateOrderStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderResponse"];
                        "application/json": components["schemas"]["OrderResponse"];
                        "text/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Precondition Failed */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The 16 SADC countries we serve and the ISO 4217 currencies permitted for each.
         * @description Namibia, Lesotho and Eswatini (Common Monetary Area) also accept ZAR. Zimbabwe accepts ZWL and USD.
         *     Use `minorUnits` to format amounts and to limit decimal places in price inputs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CountryResponse"][];
                        "application/json": components["schemas"]["CountryResponse"][];
                        "text/json": components["schemas"]["CountryResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/top-spenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top customers by spend over a recent window, including customers who spent nothing.
         * @description Ranks every customer whose country can order in `currency` (for ZAR that includes the CMA countries),
         *     highest spend first. Customers with no qualifying orders are listed with a total of 0.
         */
        get: {
            parameters: {
                query?: {
                    /** @description ISO 4217. Spend is never summed across currencies. */
                    currency?: string;
                    /** @description Look-back window in days (1–366). Default 90. */
                    days?: number;
                    /** @description How many customers to return (1–100). Default 10. */
                    top?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TopSpendersResponse"];
                        "application/json": components["schemas"]["TopSpendersResponse"];
                        "text/json": components["schemas"]["TopSpendersResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/customers/{customerId}/running-totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A customer's cumulative spend, order by order, in one currency. */
        get: {
            parameters: {
                query?: {
                    /** @description ISO 4217. Must be a currency the customer's country may order in. */
                    currency?: string;
                };
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RunningTotalsResponse"];
                        "application/json": components["schemas"]["RunningTotalsResponse"];
                        "text/json": components["schemas"]["RunningTotalsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CountryResponse: {
            /** @description ISO 3166-1 alpha-2, e.g. `ZA`. */
            code: string;
            /** @description Display name. */
            name: string;
            /** @description True for ZA, NA, LS and SZ. */
            isCommonMonetaryArea: boolean;
            /** @description Currencies customers in this country may order in, local currency first. */
            currencies: components["schemas"]["CurrencyResponse"][];
        };
        CreateCustomerRequest: {
            /** @description Full name or company name, up to 200 characters. */
            name?: string | null;
            /** @description Unique (case-insensitive) email address, up to 320 characters. */
            email?: string | null;
            /** @description ISO 3166-1 alpha-2 code of a SADC member state, e.g. `ZA`. */
            countryCode?: string | null;
        };
        CreateOrderLineRequest: {
            /** @description Up to 64 characters; stored upper case. */
            productSku?: string | null;
            /**
             * Format: int32
             * @description At least 1.
             */
            quantity?: number;
            /**
             * Format: double
             * @description In the order's currency, ≥ 0, with no more decimals than the currency allows.
             */
            unitPrice?: number;
        };
        CreateOrderRequest: {
            /**
             * Format: uuid
             * @description An existing customer. Their country decides which currencies are allowed.
             */
            customerId?: string | null;
            /** @description ISO 4217, e.g. `ZAR`. Must be permitted for the customer's country. */
            currencyCode?: string | null;
            /** @description 1 to 100 lines. Each SKU may appear once. */
            lineItems?: components["schemas"]["CreateOrderLineRequest"][] | null;
        };
        CurrencyResponse: {
            /** @description ISO 4217, e.g. `ZAR`. */
            code: string;
            /** @description Display name. */
            name: string;
            /**
             * Format: int32
             * @description Decimal places the currency uses (KMF uses 0).
             */
            minorUnits: number;
        };
        CustomerResponse: {
            /**
             * Format: uuid
             * @description Customer ID.
             */
            id: string;
            /** @description Name as entered (trimmed). */
            name: string;
            /** @description Email, lower-cased. */
            email: string;
            /** @description ISO 3166-1 alpha-2, upper case. */
            countryCode: string;
            /**
             * Format: date-time
             * @description UTC.
             */
            createdAt: string;
        };
        /** @description A page of results plus the metadata a UI needs to render pagination. */
        CustomerResponsePagedResult: {
            items: components["schemas"]["CustomerResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasPrevious: boolean;
            readonly hasNext: boolean;
        };
        DevTokenRequest: {
            /** @description Display name put in the token's `name` claim. */
            name?: string | null;
            /** @description App roles to grant: any of Orders.Read, Orders.Write, Orders.Admin. */
            roles?: string[] | null;
        };
        DevTokenResponse: {
            /** @description JWT to send as `Authorization: Bearer <token>`. */
            accessToken: string;
            /** @description Always `Bearer`. */
            tokenType: string;
            /**
             * Format: int32
             * @description Lifetime in seconds.
             */
            expiresIn: number;
            /** @description Roles granted. */
            roles: string[];
        };
        OrderLineItemResponse: {
            /** Format: uuid */
            id: string;
            productSku: string;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            unitPrice: number;
            /** Format: double */
            lineTotal: number;
        };
        OrderResponse: {
            /**
             * Format: uuid
             * @description Order ID.
             */
            id: string;
            /**
             * Format: uuid
             * @description Owning customer.
             */
            customerId: string;
            status: components["schemas"]["OrderStatus"];
            /** @description ISO 4217. */
            currencyCode: string;
            /**
             * Format: double
             * @description Σ(quantity × unitPrice), computed by the server.
             */
            totalAmount: number;
            /**
             * Format: date-time
             * @description UTC.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description UTC time stock was allocated, or null.
             */
            allocatedAt?: string | null;
            /** @description Statuses this order can move to next, so clients only offer legal actions. */
            allowedTransitions: components["schemas"]["OrderStatus"][];
            /** @description The order's lines. */
            lineItems: components["schemas"]["OrderLineItemResponse"][];
        };
        /** @enum {string} */
        OrderStatus: "Pending" | "Paid" | "Fulfilled" | "Cancelled";
        /** @description A row in the order list (no line items, to keep list queries on the covering index). */
        OrderSummaryResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerId: string;
            customerName: string;
            status: components["schemas"]["OrderStatus"];
            currencyCode: string;
            /** Format: double */
            totalAmount: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description A page of results plus the metadata a UI needs to render pagination. */
        OrderSummaryResponsePagedResult: {
            items: components["schemas"]["OrderSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasPrevious: boolean;
            readonly hasNext: boolean;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        RunningTotalPoint: {
            /**
             * Format: uuid
             * @description Order ID.
             */
            orderId: string;
            /**
             * Format: date-time
             * @description UTC.
             */
            createdAt: string;
            status: components["schemas"]["OrderStatus"];
            /**
             * Format: double
             * @description This order's total.
             */
            totalAmount: number;
            /**
             * Format: double
             * @description Cumulative spend up to and including this order.
             */
            runningTotal: number;
        };
        RunningTotalsResponse: {
            /** Format: uuid */
            customerId: string;
            currencyCode: string;
            orders: components["schemas"]["RunningTotalPoint"][];
        };
        TopSpenderResponse: {
            /**
             * Format: int32
             * @description 1-based position.
             */
            rank: number;
            /**
             * Format: uuid
             * @description Customer ID.
             */
            customerId: string;
            /** @description Customer name. */
            name: string;
            /** @description ISO 3166-1 alpha-2. */
            countryCode: string;
            /**
             * Format: double
             * @description Sum of Paid and Fulfilled orders in the window.
             */
            totalSpend: number;
            /**
             * Format: int32
             * @description Number of those orders.
             */
            orderCount: number;
        };
        TopSpendersResponse: {
            /** @description The single currency all amounts are in. */
            currencyCode: string;
            /**
             * Format: date-time
             * @description Start of the window (inclusive).
             */
            sinceUtc: string;
            /**
             * Format: date-time
             * @description When the report was produced.
             */
            untilUtc: string;
            /** @description Ranked by spend; customers without qualifying orders appear with 0. */
            customers: components["schemas"]["TopSpenderResponse"][];
        };
        UpdateOrderStatusRequest: {
            /** @description Target status: `Paid`, `Fulfilled` or `Cancelled`. */
            status?: string | null;
        };
        ValidationProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            errors?: {
                [key: string]: string[];
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
