<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrderManagement.Domain\OrderManagement.Domain.csproj" />
    <ProjectReference Include="..\OrderManagement.Contracts\OrderManagement.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

</Project>
